pipeline:
  identifier: Build_rahultyagi624_samples_1704104035215
  name: Build samples
  orgIdentifier: default
  projectIdentifier: dotnet_demo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698398634837
        repoName: rahultyagi624/samples
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
