pipeline:
  identifier: Build_rahultyagi624_samples_1704109639938
  name: Build samples
  orgIdentifier: default
  projectIdentifier: new_demo2
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: rahultyagi624/samples
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: |
                      cd /harness
                      ls
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: npm install
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
